mmCreateView("ospray", "View3D_2", "::ospray::View3D_21")
mmCreateModule("OSPRayRenderer", "::ospray::OSPRayRenderer1")
mmSetParamValue("::ospray::OSPRayRenderer1::useDBcomponent", "true")
mmCreateModule("AmbientLight", "::ospray::AmbientLight1")
mmCreateModule("OSPRaySphereGeometry", "::ospray::OSPRaySphereGeometry1")
mmCreateModule("OSPRayOBJMaterial", "::ospray::OSPRayOBJMaterial1")
mmCreateModule("StaticMMPLDProvider", "::ospray::StaticMMPLDProvider1")
mmSetParamValue("::ospray::StaticMMPLDProvider1::filenames", "../sampledata/part_rnk000000.mmpld")
mmCreateModule("BoundingBoxRenderer", "::ospray::BoundingBoxRenderer1")
mmCreateModule("ScreenShooter", "::ospray::ScreenShooter1")

mmSetParamValue("::ospray::ScreenShooter1::filename", "ospray_renderer.png")
mmSetParamValue("::ospray::ScreenShooter1::view", "::ospray::View3D_21")

mmCreateCall("CallLight", "::ospray::OSPRayRenderer1::lights", "::ospray::AmbientLight1::deployLightSlot")
mmCreateCall("CallOSPRayStructure", "::ospray::OSPRayRenderer1::getStructure", "::ospray::OSPRaySphereGeometry1::deployStructureSlot")
mmCreateCall("CallOSPRayMaterial", "::ospray::OSPRaySphereGeometry1::getMaterialSlot", "::ospray::OSPRayOBJMaterial1::deployMaterialSlot")
mmCreateCall("MultiParticleDataCall", "::ospray::OSPRaySphereGeometry1::getdata", "::ospray::StaticMMPLDProvider1::outData")
mmCreateCall("CallRender3D_2", "::ospray::BoundingBoxRenderer1::chainRendering", "::ospray::OSPRayRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::ospray::View3D_21::rendering", "::ospray::BoundingBoxRenderer1::rendering")
