--[[ generated by MegaMol Configurator 1.2.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "E:\new_tmp\megamol-examples\ospray\testspheres_ospray.lua" -i Project_1 inst
in PowerShell:
  -p "E:\new_tmp\megamol-examples\ospray\testspheres_ospray.lua" -i Project_1 inst

 --]]

mmCreateView("Project_1", "GUIView", "GUIView1")
mmCreateModule("OSPRayRenderer", "::Project_1::OSPRayRenderer1")
mmCreateModule("AmbientLight", "::Project_1::AmbientLight1")
mmCreateModule("OSPRaySphereGeometry", "::Project_1::OSPRaySphereGeometry1")
mmCreateModule("View3D_2", "::Project_1::View3D_21")
mmCreateModule("OSPRayOBJMaterial", "::Project_1::OSPRayOBJMaterial1")
mmCreateModule("TestSpheresDataSource", "::Project_1::TestSpheresDataSource1")
mmCreateCall("CallLight", "::Project_1::OSPRayRenderer1::lights", "::Project_1::AmbientLight1::deployLightSlot")
mmCreateCall("CallOSPRayStructure", "::Project_1::OSPRayRenderer1::getStructure", "::Project_1::OSPRaySphereGeometry1::deployStructureSlot")
mmCreateCall("CallRender3D_2", "::Project_1::View3D_21::rendering", "::Project_1::OSPRayRenderer1::rendering")
mmCreateCall("CallRenderView", "::Project_1::GUIView1::renderview", "::Project_1::View3D_21::render")
mmCreateCall("CallOSPRayMaterial", "::Project_1::OSPRaySphereGeometry1::getMaterialSlot", "::Project_1::OSPRayOBJMaterial1::deployMaterialSlot")
mmCreateCall("MultiParticleDataCall", "::Project_1::OSPRaySphereGeometry1::getdata", "::Project_1::TestSpheresDataSource1::getData")
