mmCreateView("picviewer", "GUIView", "GUIView1")
mmCreateModule("View3D_2", "::picviewer::view")
mmCreateModule("ImageViewer", "::picviewer::ImageViewer1")
mmSetParamValue("::picviewer::ImageViewer1::pasteFiles", "..\\examples\\imageviewer\\Epic_Win_title_card.png")
mmCreateModule("BoundingBoxRenderer", "::picviewer::bboxRenderer")
mmCreateModule("ScreenShooter", "::picviewer::ScreenShooter1")
mmSetParamValue("::picviewer::ScreenShooter1::view", "::picviewer::view")
mmSetParamValue("::picviewer::ScreenShooter1::imgWidth", "1920")
mmSetParamValue("::picviewer::ScreenShooter1::imgHeight", "1080")
mmSetParamValue("::picviewer::ScreenShooter1::tileWidth", "1920")
mmSetParamValue("::picviewer::ScreenShooter1::tileHeight", "1080")
mmSetParamValue("::picviewer::ScreenShooter1::filename", "../examples/imageviewer/picviewer.png")
mmCreateCall("CallRenderView", "::picviewer::GUIView1::renderview", "::picviewer::view::render")
mmCreateCall("CallRender3D_2", "::picviewer::view::rendering", "::picviewer::bboxRenderer::rendering")
mmCreateCall("CallRender3D_2", "::picviewer::bboxRenderer::chainRendering", "::picviewer::ImageViewer1::rendering")
--mmSetParamValue("::picviewer::ScreenShooter1::trigger", " ")
