--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "E:\github\megamol\examples\CompositingExample.lua" -i Project_1 inst
in PowerShell:
  -p "E:\github\megamol\examples\CompositingExample.lua" -i Project_1 inst

 --]]

mmCreateView("Project_1", "GUIView", "GUIView1") --confPos={X=10,Y=10}
mmCreateModule("View3D_2", "::Project_1::View3D_21") --confPos={X=94,Y=115}
mmSetParamValue("::Project_1::View3D_21::cam::position", [=[0.404329;0.262860;0.418094]=])
mmSetParamValue("::Project_1::View3D_21::cam::orientation", [=[-0.198369;0.364952;0.079895;0.906132]=])
mmSetParamValue("::Project_1::View3D_21::cam::nearplane", [=[0.002441]=])
mmSetParamValue("::Project_1::View3D_21::cam::farplane", [=[2.440673]=])
mmSetParamValue("::Project_1::View3D_21::cam::convergenceplane", [=[0.000000]=])
mmSetParamValue("::Project_1::View3D_21::cam::halfapertureradians", [=[0.261799]=])
mmSetParamValue("::Project_1::View3D_21::cam::halfdisparity", [=[0.025000]=])
mmCreateModule("DrawToScreen", "::Project_1::DrawToScreen1") --confPos={X=301,Y=36}
mmCreateModule("BoundingBoxRenderer", "::Project_1::BoundingBoxRenderer1") --confPos={X=151,Y=230}
mmCreateModule("RenderMDIMesh", "::Project_1::RenderMDIMesh1") --confPos={X=548,Y=577}
mmCreateModule("GlTFRenderTasksDataSource", "::Project_1::GlTFRenderTasksDataSource1") --confPos={X=771,Y=735}
mmCreateModule("SimpleGPUMtlDataSource", "::Project_1::SimpleGPUMtlDataSource1") --confPos={X=1164,Y=688}
mmSetParamValue("::Project_1::SimpleGPUMtlDataSource1::BTF filename", [=[dfr_gltfExample]=])
mmCreateModule("GPUMeshes", "::Project_1::GPUMeshes1") --confPos={X=1124,Y=764}
mmCreateModule("GlTFFileLoader", "::Project_1::GlTFFileLoader1") --confPos={X=1270,Y=837}
mmSetParamValue("::Project_1::GlTFFileLoader1::glTF filename", [=[..\examples\mesh\WaterBottle\glTF\WaterBottle.gltf]=])
mmCreateModule("SimpleRenderTarget", "::Project_1::SimpleRenderTarget1") --confPos={X=1267,Y=271}
mmCreateModule("LocalLighting", "::Project_1::LocalLighting1") --confPos={X=981,Y=24}
mmCreateModule("ScreenSpaceEffect", "::Project_1::FXAA") --confPos={X=552,Y=69}
mmSetParamValue("::Project_1::FXAA::Mode", [=[1]=])
mmCreateModule("TextureCombine", "::Project_1::TextureCombine1") --confPos={X=777,Y=133}
mmSetParamValue("::Project_1::TextureCombine1::Mode", [=[1]=])
mmCreateModule("ScreenSpaceEffect", "::Project_1::SSAO") --confPos={X=949,Y=256}
mmSetParamValue("::Project_1::SSAO::SSAO Samples", [=[32]=])
mmSetParamValue("::Project_1::SSAO::SSAO Radius", [=[0.010000]=])
mmCreateModule("DistantLight", "::Project_1::DistantLight1") --confPos={X=1256,Y=34}
mmSetParamValue("::Project_1::DistantLight1::Direction", [=[1.000000;1.000000;1.000000]=])
mmCreateCall("CallRenderView", "::Project_1::GUIView1::renderview", "::Project_1::View3D_21::render")
mmCreateCall("CallRender3D_2", "::Project_1::BoundingBoxRenderer1::chainRendering", "::Project_1::DrawToScreen1::rendering")
mmCreateCall("CallRender3D_2", "::Project_1::View3D_21::rendering", "::Project_1::BoundingBoxRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::Project_1::DrawToScreen1::chainRendering", "::Project_1::RenderMDIMesh1::rendering")
mmCreateCall("CallGPURenderTaskData", "::Project_1::RenderMDIMesh1::getRenderTaskData", "::Project_1::GlTFRenderTasksDataSource1::getData")
mmCreateCall("CallGPUMaterialData", "::Project_1::GlTFRenderTasksDataSource1::getMaterialData", "::Project_1::SimpleGPUMtlDataSource1::getData")
mmCreateCall("CallGPUMeshData", "::Project_1::GlTFRenderTasksDataSource1::getMeshData", "::Project_1::GPUMeshes1::getData")
mmCreateCall("CallMesh", "::Project_1::GPUMeshes1::CallMeshes", "::Project_1::GlTFFileLoader1::CallMeshData")
mmCreateCall("CallGlTFData", "::Project_1::GlTFRenderTasksDataSource1::CallGlTFData", "::Project_1::GlTFFileLoader1::CallGlTFData")
mmCreateCall("CallRender3D_2", "::Project_1::RenderMDIMesh1::chainRendering", "::Project_1::SimpleRenderTarget1::rendering")
mmCreateCall("CallTexture2D", "::Project_1::LocalLighting1::AlbedoTexture", "::Project_1::SimpleRenderTarget1::Color")
mmCreateCall("CallTexture2D", "::Project_1::DrawToScreen1::InputTexture", "::Project_1::FXAA::OutputTexture")
mmCreateCall("CallTexture2D", "::Project_1::TextureCombine1::InputTexture0", "::Project_1::LocalLighting1::OutputTexture")
mmCreateCall("CallTexture2D", "::Project_1::TextureCombine1::InputTexture1", "::Project_1::SSAO::OutputTexture")
mmCreateCall("CallTexture2D", "::Project_1::SSAO::NormalTexture", "::Project_1::SimpleRenderTarget1::Normals")
mmCreateCall("CallTexture2D", "::Project_1::SSAO::DepthTexture", "::Project_1::SimpleRenderTarget1::Depth")
mmCreateCall("CallCamera", "::Project_1::SSAO::Camera", "::Project_1::SimpleRenderTarget1::Camera")
mmCreateCall("CallCamera", "::Project_1::LocalLighting1::Camera", "::Project_1::SimpleRenderTarget1::Camera")
mmCreateCall("CallTexture2D", "::Project_1::LocalLighting1::DepthTexture", "::Project_1::SimpleRenderTarget1::Depth")
mmCreateCall("CallTexture2D", "::Project_1::LocalLighting1::NormalTexture", "::Project_1::SimpleRenderTarget1::Normals")
mmCreateCall("CallLight", "::Project_1::LocalLighting1::lights", "::Project_1::DistantLight1::deployLightSlot")
mmCreateCall("CallTexture2D", "::Project_1::FXAA::InputTexture", "::Project_1::TextureCombine1::OutputTexture")
