--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "E:\github\megamol\examples\CompositingExample.lua" -i CompositingExample inst
in PowerShell:
  -p "E:\github\megamol\examples\CompositingExample.lua" -i CompositingExample inst

 --]]

mmCreateView("CompositingExample", "GUIView", "GUIView1")
mmCreateModule("DrawToScreen", "::CompositingExample::DrawToScreen1")
mmCreateModule("View3D_2", "::CompositingExample::View3D_21")
mmSetParamValue("::CompositingExample::View3D_21::viewKey::MoveStep", "1")
mmSetParamValue("::CompositingExample::View3D_21::cam::position", "0;0;5")
mmSetParamValue("::CompositingExample::View3D_21::cam::orientation", "0;0;0;1")
mmSetParamValue("::CompositingExample::View3D_21::cam::nearplane", "2.923084")
mmSetParamValue("::CompositingExample::View3D_21::cam::farplane", "2923.083984")
mmSetParamValue("::CompositingExample::View3D_21::cam::convergenceplane", "0")
mmSetParamValue("::CompositingExample::View3D_21::cam::halfapertureradians", "0.261799")
mmSetParamValue("::CompositingExample::View3D_21::cam::halfdisparity", "0.025")
mmSetParamValue("::CompositingExample::GUIView1::state", "{
  \"Font Settings\": {
    \"font_name\": \"\",
    \"fpsms_max_history_count\": 20,
    \"fpsms_mode\": 0,
    \"fpsms_refresh_rate\": 2.0,
    \"fpsms_show_options\": false,
    \"main_project_file\": \"\",
    \"param_module_filter\": 0,
    \"param_modules_list\": [],
    \"param_show_hotkeys\": false,
    \"win_callback\": 4,
    \"win_flags\": 64,
    \"win_hotkey\": [
      299,
      2
    ],
    \"win_position\": [
      12.0,
      12.0
    ],
    \"win_reset_size\": [
      500.0,
      300.0
    ],
    \"win_show\": false,
    \"win_size\": [
      250.0,
      600.0
    ],
    \"win_soft_reset\": true
  },
  \"Main Window\": {
    \"font_name\": \"\",
    \"fpsms_max_history_count\": 20,
    \"fpsms_mode\": 0,
    \"fpsms_refresh_rate\": 2.0,
    \"fpsms_show_options\": false,
    \"main_project_file\": \"\",
    \"param_module_filter\": 0,
    \"param_modules_list\": [],
    \"param_show_hotkeys\": false,
    \"win_callback\": 1,
    \"win_flags\": 3073,
    \"win_hotkey\": [
      301,
      2
    ],
    \"win_position\": [
      24.0,
      12.0
    ],
    \"win_reset_size\": [
      500.0,
      300.0
    ],
    \"win_show\": true,
    \"win_size\": [
      250.0,
      600.0
    ],
    \"win_soft_reset\": false
  },
  \"Performance Metrics\": {
    \"font_name\": \"\",
    \"fpsms_max_history_count\": 20,
    \"fpsms_mode\": 0,
    \"fpsms_refresh_rate\": 2.0,
    \"fpsms_show_options\": false,
    \"main_project_file\": \"\",
    \"param_module_filter\": 0,
    \"param_modules_list\": [],
    \"param_show_hotkeys\": false,
    \"win_callback\": 3,
    \"win_flags\": 65,
    \"win_hotkey\": [
      300,
      2
    ],
    \"win_position\": [
      12.0,
      12.0
    ],
    \"win_reset_size\": [
      500.0,
      300.0
    ],
    \"win_show\": false,
    \"win_size\": [
      250.0,
      600.0
    ],
    \"win_soft_reset\": true
  },
  \"Transfer Function Editor\": {
    \"font_name\": \"\",
    \"fpsms_max_history_count\": 20,
    \"fpsms_mode\": 0,
    \"fpsms_refresh_rate\": 2.0,
    \"fpsms_show_options\": false,
    \"main_project_file\": \"\",
    \"param_module_filter\": 0,
    \"param_modules_list\": [],
    \"param_show_hotkeys\": false,
    \"win_callback\": 5,
    \"win_flags\": 64,
    \"win_hotkey\": [
      298,
      2
    ],
    \"win_position\": [
      12.0,
      12.0
    ],
    \"win_reset_size\": [
      500.0,
      300.0
    ],
    \"win_show\": false,
    \"win_size\": [
      250.0,
      600.0
    ],
    \"win_soft_reset\": true
  }
}")
mmCreateModule("GlTFRenderTasksDataSource", "::CompositingExample::GlTFRenderTasksDataSource1")
mmCreateModule("SimpleGPUMtlDataSource", "::CompositingExample::SimpleGPUMtlDataSource1")
mmSetParamValue("::CompositingExample::SimpleGPUMtlDataSource1::BTF filename", "dfr_gltfExample")
mmCreateModule("GlTFMeshesDataSource", "::CompositingExample::GlTFMeshesDataSource1")
mmCreateModule("GlTFFileLoader", "::CompositingExample::GlTFFileLoader1")
mmSetParamValue("::CompositingExample::GlTFFileLoader1::glTF filename", "..\\examples\\mesh\\WaterBottle\\glTF\\WaterBottle.gltf")
mmCreateModule("PointLight", "::CompositingExample::PointLight1")
mmSetParamValue("::CompositingExample::PointLight1::Intensity", "2000000.000000")
mmSetParamValue("::CompositingExample::PointLight1::Position", "0.000000;0.000000;-2500.000000")
mmCreateModule("PointLight", "::CompositingExample::PointLight2")
mmSetParamValue("::CompositingExample::PointLight2::Intensity", "15000")
mmSetParamValue("::CompositingExample::PointLight2::Position", "-200.000000;250.000000;-200.000000")
mmCreateModule("ScreenSpaceEffect", "::CompositingExample::SSAO")
mmSetParamValue("::CompositingExample::SSAO::SSAO Radius", "0.05")
mmCreateModule("TextureCombine", "::CompositingExample::TextureCombine1")
mmSetParamValue("::CompositingExample::TextureCombine1::Mode", "1")
mmCreateModule("PointLight", "::CompositingExample::PointLight3")
mmSetParamValue("::CompositingExample::PointLight3::Intensity", "10000000.000000")
mmSetParamValue("::CompositingExample::PointLight3::Position", "0.000000;2500.000000;0.000000")
mmCreateModule("SimpleRenderTarget", "::CompositingExample::SimpleRenderTarget1")
mmCreateModule("LocalLighting", "::CompositingExample::Lambert")
mmCreateModule("RenderMDIMesh", "::CompositingExample::RenderMDIMesh1")
mmCreateModule("ScreenSpaceEffect", "::CompositingExample::FXAA")
mmSetParamValue("::CompositingExample::FXAA::Mode", "1")
mmCreateModule("BoundingBoxRenderer", "::CompositingExample::BoundingBoxRenderer1")
mmCreateCall("CallRenderView", "::CompositingExample::GUIView1::renderview", "::CompositingExample::View3D_21::render")
mmCreateCall("CallGPUMaterialData", "::CompositingExample::GlTFRenderTasksDataSource1::getMaterialData", "::CompositingExample::SimpleGPUMtlDataSource1::getData")
mmCreateCall("CallGPUMeshData", "::CompositingExample::GlTFRenderTasksDataSource1::getMeshData", "::CompositingExample::GlTFMeshesDataSource1::getData")
mmCreateCall("CallGlTFData", "::CompositingExample::GlTFMeshesDataSource1::CallGlTFData", "::CompositingExample::GlTFFileLoader1::CallGlTFData")
mmCreateCall("CallGlTFData", "::CompositingExample::GlTFRenderTasksDataSource1::CallGlTFData", "::CompositingExample::GlTFFileLoader1::CallGlTFData")
mmCreateCall("CallLight", "::CompositingExample::PointLight1::getLightSlot", "::CompositingExample::PointLight2::deployLightSlot")
mmCreateCall("CallLight", "::CompositingExample::PointLight2::getLightSlot", "::CompositingExample::PointLight3::deployLightSlot")
mmCreateCall("CallCamera", "::CompositingExample::SSAO::Camera", "::CompositingExample::SimpleRenderTarget1::Camera")
mmCreateCall("CallTexture2D", "::CompositingExample::SSAO::DepthTexture", "::CompositingExample::SimpleRenderTarget1::Depth")
mmCreateCall("CallTexture2D", "::CompositingExample::SSAO::NormalTexture", "::CompositingExample::SimpleRenderTarget1::Normals")
mmCreateCall("CallTexture2D", "::CompositingExample::Lambert::AlbedoTexture", "::CompositingExample::SimpleRenderTarget1::Color")
mmCreateCall("CallTexture2D", "::CompositingExample::Lambert::NormalTexture", "::CompositingExample::SimpleRenderTarget1::Normals")
mmCreateCall("CallTexture2D", "::CompositingExample::Lambert::DepthTexture", "::CompositingExample::SimpleRenderTarget1::Depth")
mmCreateCall("CallLight", "::CompositingExample::Lambert::lights", "::CompositingExample::PointLight1::deployLightSlot")
mmCreateCall("CallCamera", "::CompositingExample::Lambert::Camera", "::CompositingExample::SimpleRenderTarget1::Camera")
mmCreateCall("CallGPURenderTaskData", "::CompositingExample::RenderMDIMesh1::getRenderTaskData", "::CompositingExample::GlTFRenderTasksDataSource1::getData")
mmCreateCall("CallTexture2D", "::CompositingExample::TextureCombine1::InputTexture0", "::CompositingExample::Lambert::OutputTexture")
mmCreateCall("CallTexture2D", "::CompositingExample::TextureCombine1::InputTexture1", "::CompositingExample::SSAO::OutputTexture")
mmCreateCall("CallTexture2D", "::CompositingExample::FXAA::InputTexture", "::CompositingExample::TextureCombine1::OutputTexture")
mmCreateCall("CallRender3D_2", "::CompositingExample::BoundingBoxRenderer1::chainRendering", "::CompositingExample::DrawToScreen1::rendering")
mmCreateCall("CallRender3D_2", "::CompositingExample::SimpleRenderTarget1::chainRendering", "::CompositingExample::RenderMDIMesh1::rendering")
mmCreateCall("CallFramebufferGL", "::CompositingExample::SimpleRenderTarget1::Framebuffer", "::CompositingExample::RenderMDIMesh1::Framebuffer")
mmCreateCall("CallRender3D_2", "::CompositingExample::DrawToScreen1::chainRendering", "::CompositingExample::SimpleRenderTarget1::rendering")
mmCreateCall("CallRender3D_2", "::CompositingExample::View3D_21::rendering", "::CompositingExample::BoundingBoxRenderer1::rendering")
mmCreateCall("CallTexture2D", "::CompositingExample::DrawToScreen1::InputTexture", "::CompositingExample::FXAA::OutputTexture")
