--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "F:\Uni\HiWi\Testing\bin\deferredShading_gltfViewer.lua" -i Project_4 inst
in PowerShell:
  -p "F:\Uni\HiWi\Testing\bin\deferredShading_gltfViewer.lua" -i Project_4 inst

 --]]

mmCreateView("Project_4", "GUIView", "GUIView1") --confPos={X=10,Y=10}
mmCreateModule("DeferredShading", "::Project_4::DeferredShading1") --confPos={X=277,Y=284}
mmSetParamValue("::Project_4::DeferredShading1::BTF filename", [=[dfrLambert]=])
mmCreateModule("View3D_2", "::Project_4::View3D_21") --confPos={X=21,Y=128}
mmCreateModule("GlTFRenderTasksDataSource", "::Project_4::GlTFRenderTasksDataSource1") --confPos={X=527,Y=208}
mmCreateModule("SimpleGPUMtlDataSource", "::Project_4::SimpleGPUMtlDataSource1") --confPos={X=827,Y=41}
mmSetParamValue("::Project_4::SimpleGPUMtlDataSource1::BTF filename", [=[dfr_gltfExample]=])
mmCreateModule("GlTFFileLoader", "::Project_4::GlTFFileLoader1") --confPos={X=865,Y=355}
mmSetParamValue("::Project_4::GlTFFileLoader1::glTF filename", [=[../examples/mesh/WaterBottle/glTF/WaterBottle.gltf]=])
mmCreateModule("PointLight", "::Project_4::PointLight1") --confPos={X=359,Y=407}
mmSetParamValue("::Project_4::PointLight1::Intensity", [=[2]=])
mmSetParamValue("::Project_4::PointLight1::Position", [=[-5.000000;5.000000;5.000000]=])
mmCreateModule("BoundingBoxRenderer", "::Project_4::BoundingBoxRenderer1") --confPos={X=14,Y=265}
mmCreateModule("PointLight", "::Project_4::PointLight2") --confPos={X=590,Y=423}
mmSetParamValue("::Project_4::PointLight2::Intensity", [=[2]=])
mmSetParamValue("::Project_4::PointLight2::Position", [=[-5.000000;5.000000;5.000000]=])
mmCreateModule("RenderMDIMesh", "::Project_4::RenderMDIMesh1") --confPos={X=397,Y=27}
mmCreateModule("GPUMeshes", "::Project_4::GPUMeshes1") --confPos={X=870,Y=182}
mmCreateCall("CallLight", "::Project_4::PointLight1::getLightSlot", "::Project_4::PointLight2::deployLightSlot")
mmCreateCall("CallRenderView", "::Project_4::GUIView1::renderview", "::Project_4::View3D_21::render")
mmCreateCall("CallRender3D_2", "::Project_4::View3D_21::rendering", "::Project_4::BoundingBoxRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::Project_4::DeferredShading1::chainRendering", "::Project_4::RenderMDIMesh1::rendering")
mmCreateCall("CallGPUMaterialData", "::Project_4::GlTFRenderTasksDataSource1::getMaterialData", "::Project_4::SimpleGPUMtlDataSource1::getData")
mmCreateCall("CallGlTFData", "::Project_4::GlTFRenderTasksDataSource1::CallGlTFData", "::Project_4::GlTFFileLoader1::CallGlTFData")
mmCreateCall("CallGPUMeshData", "::Project_4::GlTFRenderTasksDataSource1::getMeshData", "::Project_4::GPUMeshes1::getData")
mmCreateCall("CallMesh", "::Project_4::GPUMeshes1::CallMeshes", "::Project_4::GlTFFileLoader1::CallMeshData")
mmCreateCall("CallLight", "::Project_4::DeferredShading1::lights", "::Project_4::PointLight1::deployLightSlot")
mmCreateCall("CallRender3D_2", "::Project_4::BoundingBoxRenderer1::chainRendering", "::Project_4::DeferredShading1::rendering")
mmCreateCall("CallGPURenderTaskData", "::Project_4::RenderMDIMesh1::getRenderTaskData", "::Project_4::GlTFRenderTasksDataSource1::getData")
