--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "C:\temp\megamol\examples\gltfViewer.lua" -i Project_1 inst
in PowerShell:
  -p "C:\temp\megamol\examples\gltfViewer.lua" -i Project_1 inst

 --]]

mmCreateView("Project_1", "GUIView", "GUIView1")
mmCreateModule("RenderMDIMesh", "::Project_1::RenderMDIMesh1")
mmCreateModule("View3DGL", "::Project_1::View3DGL1")
mmCreateModule("GlTFRenderTasksDataSource", "::Project_1::GlTFRenderTasksDataSource1")
mmCreateModule("SimpleGPUMtlDataSource", "::Project_1::SimpleGPUMtlDataSource1")
mmSetParamValue("::Project_1::SimpleGPUMtlDataSource1::BTF filename", "gltfExample")
mmCreateModule("GlTFMeshesDataSource", "::Project_1::GlTFMeshesDataSource1")
mmCreateModule("GlTFFileLoader", "::Project_1::GlTFFileLoader1")
mmSetParamValue("::Project_1::GlTFFileLoader1::glTF filename", "../examples/mesh/WaterBottle/glTF/WaterBottle.gltf")
mmCreateCall("CallRender3DGL", "::Project_1::View3DGL1::rendering", "::Project_1::RenderMDIMesh1::rendering")
mmCreateCall("CallRenderViewGL", "::Project_1::GUIView1::renderview", "::Project_1::View3DGL1::render")
mmCreateCall("CallGPURenderTaskData", "::Project_1::RenderMDIMesh1::getRenderTaskData", "::Project_1::GlTFRenderTasksDataSource1::getData")
mmCreateCall("CallGPUMaterialData", "::Project_1::GlTFRenderTasksDataSource1::getMaterialData", "::Project_1::SimpleGPUMtlDataSource1::getData")
mmCreateCall("CallGPUMeshData", "::Project_1::GlTFRenderTasksDataSource1::getMeshData", "::Project_1::GlTFMeshesDataSource1::getData")
mmCreateCall("CallGlTFData", "::Project_1::GlTFMeshesDataSource1::getGlTFFile", "::Project_1::GlTFFileLoader1::getData")
mmCreateCall("CallGlTFData", "::Project_1::GlTFRenderTasksDataSource1::getGlTFFile", "::Project_1::GlTFFileLoader1::getData")
