mmCreateView("infovis", "SplitViewGL","::SplitViewGL_1")
mmCreateModule("View2DGL","::View2DGL_1")
mmCreateModule("View2DGL","::View2DGL_2")
mmCreateModule("ScatterplotMatrixRenderer2D","::ScatterplotMatrixRenderer2D_1") 
mmCreateModule("ParallelCoordinatesRenderer2D","::ParallelCoordinatesRenderer2D_1")
mmCreateModule("CSVDataSource","::CSVDataSource_1")
mmCreateModule("TransferFunction","::TransferFunction_1") 
mmCreateModule("UniFlagStorage","::FlagStorage_1")

mmCreateCall("CallRenderViewGL","::SplitViewGL_1::render1","::View2DGL_1::render")
mmCreateCall("CallRenderViewGL","::SplitViewGL_1::render2","::View2DGL_2::render")
mmCreateCall("CallRender2DGL","::View2DGL_1::rendering","::ScatterplotMatrixRenderer2D_1::rendering")
mmCreateCall("CallRender2DGL","::View2DGL_2::rendering","::ParallelCoordinatesRenderer2D_1::rendering")
mmCreateCall("TableDataCall","::ScatterplotMatrixRenderer2D_1::ftIn","::CSVDataSource_1::getData")
mmCreateCall("CallGetTransferFunction","::ScatterplotMatrixRenderer2D_1::tfIn","::TransferFunction_1::gettransferfunction")
mmCreateCall("FlagCallRead_GL","::ScatterplotMatrixRenderer2D_1::readFlags","::FlagStorage_1::readFlags")
mmCreateCall("FlagCallWrite_GL","::ScatterplotMatrixRenderer2D_1::writeFlags","::FlagStorage_1::writeFlags")
mmCreateCall("TableDataCall","::ParallelCoordinatesRenderer2D_1::getdata","::CSVDataSource_1::getData")
mmCreateCall("CallGetTransferFunction","::ParallelCoordinatesRenderer2D_1::getTF","::TransferFunction_1::gettransferfunction")
mmCreateCall("FlagCallRead_GL","::ParallelCoordinatesRenderer2D_1::readFlags","::FlagStorage_1::readFlags")
mmCreateCall("FlagCallWrite_GL","::ParallelCoordinatesRenderer2D_1::writeFlags","::FlagStorage_1::writeFlags")

mmSetParamValue("::CSVDataSource_1::filename",[=[../examples/sampledata/iris.csv]=])
mmSetParamValue("::CSVDataSource_1::colSep",[=[,]=])
mmSetParamValue("::CSVDataSource_1::decSep",[=[US (3.141)]=])

