mmCreateView("GraphEntry_1","SplitViewGL","::SplitViewGL_1")

mmCreateModule("View2DGL","::FilterData::View2DGL_1")
mmCreateModule("ParallelCoordinatesRenderer2D","::FilterData::ParallelCoordinatesRenderer2D_1")
mmCreateModule("CSVDataSource","::FilterData::CSVDataSource_1")
mmCreateModule("TransferFunctionGL","::FilterData::TransferFunction_1")
mmCreateModule("UniFlagStorageGL","::FilterData::UniFlagStorageGL_1")
mmCreateModule("TableFlagFilter","::FilterData::TableFlagFilter_1")
mmCreateModule("SplitViewGL","::InfoVis::SplitViewGL_2")
mmCreateModule("SplitViewGL","::InfoVis::SplitViewGL_3")
mmCreateModule("View2DGL","::InfoVis::View2DGL_2")
mmCreateModule("View2DGL","::InfoVis::View2DGL_3")
mmCreateModule("View2DGL","::InfoVis::View2DGL_4")
mmCreateModule("ScatterplotMatrixRenderer2D","::InfoVis::ScatterplotMatrixRenderer2D_1")
mmCreateModule("ParallelCoordinatesRenderer2D","::InfoVis::ParallelCoordinatesRenderer2D_2")
mmCreateModule("TableHistogramRenderer2D","::InfoVis::TableHistogramRenderer2D_1")
mmCreateModule("TransferFunctionGL","::InfoVis::TransferFunctionGL_1")
mmCreateModule("UniFlagStorageGL","::InfoVis::UniFlagStorageGL_2")

mmCreateCall("CallRenderViewGL","::SplitViewGL_1::render1","::FilterData::View2DGL_1::render")
mmCreateCall("CallRenderViewGL","::SplitViewGL_1::render2","::InfoVis::SplitViewGL_2::render")
mmCreateCall("CallRender2DGL","::FilterData::View2DGL_1::rendering","::FilterData::ParallelCoordinatesRenderer2D_1::rendering")
mmCreateCall("TableDataCall","::FilterData::ParallelCoordinatesRenderer2D_1::getData","::FilterData::CSVDataSource_1::getData")
mmCreateCall("CallGetTransferFunctionGL","::FilterData::ParallelCoordinatesRenderer2D_1::getTransferFunction","::FilterData::TransferFunction_1::gettransferfunction")
mmCreateCall("FlagCallRead_GL","::FilterData::ParallelCoordinatesRenderer2D_1::readFlagStorage","::FilterData::UniFlagStorageGL_1::readFlags")
mmCreateCall("FlagCallWrite_GL","::FilterData::ParallelCoordinatesRenderer2D_1::writeFlagStorage","::FilterData::UniFlagStorageGL_1::writeFlags")
mmCreateCall("TableDataCall","::FilterData::TableFlagFilter_1::getDataIn","::FilterData::CSVDataSource_1::getData")
mmCreateCall("FlagCallRead_CPU","::FilterData::TableFlagFilter_1::readFlagStorage","::FilterData::UniFlagStorageGL_1::readCPUFlags")
mmCreateCall("CallRenderViewGL","::InfoVis::SplitViewGL_2::render1","::InfoVis::View2DGL_2::render")
mmCreateCall("CallRenderViewGL","::InfoVis::SplitViewGL_2::render2","::InfoVis::SplitViewGL_3::render")
mmCreateCall("CallRenderViewGL","::InfoVis::SplitViewGL_3::render1","::InfoVis::View2DGL_3::render")
mmCreateCall("CallRenderViewGL","::InfoVis::SplitViewGL_3::render2","::InfoVis::View2DGL_4::render")
mmCreateCall("CallRender2DGL","::InfoVis::View2DGL_2::rendering","::InfoVis::ScatterplotMatrixRenderer2D_1::rendering")
mmCreateCall("CallRender2DGL","::InfoVis::View2DGL_3::rendering","::InfoVis::ParallelCoordinatesRenderer2D_2::rendering")
mmCreateCall("CallRender2DGL","::InfoVis::View2DGL_4::rendering","::InfoVis::TableHistogramRenderer2D_1::rendering")
mmCreateCall("TableDataCall","::InfoVis::ScatterplotMatrixRenderer2D_1::ftIn","::FilterData::TableFlagFilter_1::getDataOut")
mmCreateCall("CallGetTransferFunctionGL","::InfoVis::ScatterplotMatrixRenderer2D_1::tfIn","::InfoVis::TransferFunctionGL_1::gettransferfunction")
mmCreateCall("FlagCallRead_GL","::InfoVis::ScatterplotMatrixRenderer2D_1::readFlags","::InfoVis::UniFlagStorageGL_2::readFlags")
mmCreateCall("FlagCallWrite_GL","::InfoVis::ScatterplotMatrixRenderer2D_1::writeFlags","::InfoVis::UniFlagStorageGL_2::writeFlags")
mmCreateCall("TableDataCall","::InfoVis::ParallelCoordinatesRenderer2D_2::getData","::FilterData::TableFlagFilter_1::getDataOut")
mmCreateCall("CallGetTransferFunctionGL","::InfoVis::ParallelCoordinatesRenderer2D_2::getTransferFunction","::InfoVis::TransferFunctionGL_1::gettransferfunction")
mmCreateCall("FlagCallRead_GL","::InfoVis::ParallelCoordinatesRenderer2D_2::readFlagStorage","::InfoVis::UniFlagStorageGL_2::readFlags")
mmCreateCall("FlagCallWrite_GL","::InfoVis::ParallelCoordinatesRenderer2D_2::writeFlagStorage","::InfoVis::UniFlagStorageGL_2::writeFlags")
mmCreateCall("CallGetTransferFunctionGL","::InfoVis::TableHistogramRenderer2D_1::getTransferFunction","::InfoVis::TransferFunctionGL_1::gettransferfunction")
mmCreateCall("TableDataCall","::InfoVis::TableHistogramRenderer2D_1::getData","::FilterData::TableFlagFilter_1::getDataOut")
mmCreateCall("FlagCallRead_GL","::InfoVis::TableHistogramRenderer2D_1::readFlagStorage","::InfoVis::UniFlagStorageGL_2::readFlags")
mmCreateCall("FlagCallWrite_GL","::InfoVis::TableHistogramRenderer2D_1::writeFlagStorage","::InfoVis::UniFlagStorageGL_2::writeFlags")

mmSetParamValue("::SplitViewGL_1::split.orientation",[=[Vertical]=])
mmSetParamValue("::SplitViewGL_1::split.pos",[=[0.200000]=])
mmSetParamValue("::FilterData::CSVDataSource_1::filename",[=[../examples/sampledata/iris.csv]=])
mmSetParamValue("::FilterData::CSVDataSource_1::colSep",[=[,]=])
mmSetParamValue("::FilterData::CSVDataSource_1::decSep",[=[US (3.141)]=])
mmSetParamValue("::InfoVis::SplitViewGL_3::split.orientation",[=[Vertical]=])

mmSetGUIState([=[{"GraphStates": {"Project": {"Interfaces": {"FilterData": {"interface_slot_0": ["::FilterData::View2DGL_1::render"],"interface_slot_1": ["::FilterData::TableFlagFilter_1::getDataOut"]},"InfoVis": {"interface_slot_2": ["::InfoVis::SplitViewGL_2::render"],"interface_slot_3": ["::InfoVis::ScatterplotMatrixRenderer2D_1::ftIn","::InfoVis::ParallelCoordinatesRenderer2D_2::getData","::InfoVis::TableHistogramRenderer2D_1::getData"]}}}}}]=])
