mmCreateView("infovis","SplitViewGL","::SplitViewGL_1")

mmCreateModule("SplitViewGL","::SplitViewGL_2")
mmCreateModule("View2DGL","::View2DGL_1")
mmCreateModule("View2DGL","::View2DGL_2")
mmCreateModule("View2DGL","::View2DGL_3")
mmCreateModule("ScatterplotMatrixRenderer2D","::ScatterplotMatrixRenderer2D_1")
mmCreateModule("ParallelCoordinatesRenderer2D","::ParallelCoordinatesRenderer2D_1")
mmCreateModule("TableHistogramRenderer2D","::TableHistogramRenderer2D_1")
mmCreateModule("CSVDataSource","::CSVDataSource_1")
mmCreateModule("TransferFunctionGL","::TransferFunction_1")
mmCreateModule("UniFlagStorageGL","::UniFlagStorageGL_1")

mmCreateCall("CallRenderViewGL","::SplitViewGL_1::render1","::View2DGL_1::render")
mmCreateCall("CallRenderViewGL","::SplitViewGL_1::render2","::SplitViewGL_2::render")
mmCreateCall("CallRenderViewGL","::SplitViewGL_2::render1","::View2DGL_2::render")
mmCreateCall("CallRenderViewGL","::SplitViewGL_2::render2","::View2DGL_3::render")
mmCreateCall("CallRender2DGL","::View2DGL_1::rendering","::ScatterplotMatrixRenderer2D_1::rendering")
mmCreateCall("CallRender2DGL","::View2DGL_2::rendering","::ParallelCoordinatesRenderer2D_1::rendering")
mmCreateCall("CallRender2DGL","::View2DGL_3::rendering","::TableHistogramRenderer2D_1::rendering")
mmCreateCall("TableDataCall","::ScatterplotMatrixRenderer2D_1::ftIn","::CSVDataSource_1::getData")
mmCreateCall("CallGetTransferFunctionGL","::ScatterplotMatrixRenderer2D_1::tfIn","::TransferFunction_1::gettransferfunction")
mmCreateCall("FlagCallRead_GL","::ScatterplotMatrixRenderer2D_1::readFlags","::UniFlagStorageGL_1::readFlags")
mmCreateCall("FlagCallWrite_GL","::ScatterplotMatrixRenderer2D_1::writeFlags","::UniFlagStorageGL_1::writeFlags")
mmCreateCall("TableDataCall","::ParallelCoordinatesRenderer2D_1::getData","::CSVDataSource_1::getData")
mmCreateCall("CallGetTransferFunctionGL","::ParallelCoordinatesRenderer2D_1::getTransferFunction","::TransferFunction_1::gettransferfunction")
mmCreateCall("FlagCallRead_GL","::ParallelCoordinatesRenderer2D_1::readFlagStorage","::UniFlagStorageGL_1::readFlags")
mmCreateCall("FlagCallWrite_GL","::ParallelCoordinatesRenderer2D_1::writeFlagStorage","::UniFlagStorageGL_1::writeFlags")
mmCreateCall("CallGetTransferFunctionGL","::TableHistogramRenderer2D_1::getTransferFunction","::TransferFunction_1::gettransferfunction")
mmCreateCall("TableDataCall","::TableHistogramRenderer2D_1::getData","::CSVDataSource_1::getData")
mmCreateCall("FlagCallRead_GL","::TableHistogramRenderer2D_1::readFlagStorage","::UniFlagStorageGL_1::readFlags")
mmCreateCall("FlagCallWrite_GL","::TableHistogramRenderer2D_1::writeFlagStorage","::UniFlagStorageGL_1::writeFlags")

mmSetParamValue("::SplitViewGL_2::split.orientation",[=[Vertical]=])
mmSetParamValue("::CSVDataSource_1::filename",[=[../examples/sampledata/iris.csv]=])
mmSetParamValue("::CSVDataSource_1::colSep",[=[,]=])
mmSetParamValue("::CSVDataSource_1::decSep",[=[US (3.141)]=])
