--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "D:\sellendk\megamol\bin\megamol101.lua" -i Project_1 inst
in PowerShell:
  -p "D:\sellendk\megamol\bin\megamol101.lua" -i Project_1 inst

 --]]

mmCreateView("Project_1", "GUIView", "GUIView1") --confPos={X=10,Y=10}
mmCreateModule("ASCIISphereLoader", "::Project_1::ASCIISphereLoader1") --confPos={X=763,Y=296}
mmSetParamValue("::Project_1::ASCIISphereLoader1::filename", [=[../examples/megamol101/1m40.csv]=])
mmCreateModule("SimplestSphereRenderer", "::Project_1::SimplestSphereRenderer1") --confPos={X=228,Y=126}
mmCreateModule("SphereColoringModule", "::Project_1::SphereColoringModule1") --confPos={X=456,Y=295}
mmSetParamValue("::Project_1::SphereColoringModule1::minColor", [=[#ff0000]=])
mmSetParamValue("::Project_1::SphereColoringModule1::maxColor", [=[#ffffff]=])
mmCreateModule("View3D_2", "::Project_1::View3D_21") --confPos={X=27,Y=129}
mmSetParamValue("::Project_1::View3D_21::backCol", [=[#ffffff]=])
mmCreateModule("BoundingBoxRenderer", "::Project_1::BoundingBoxRenderer1") --confPos={X=12,Y=294}
mmSetParamValue("::Project_1::BoundingBoxRenderer1::boundingBoxColor", [=[#eeeeee]=])
mmCreateCall("CallSpheres", "::Project_1::SimplestSphereRenderer1::inData", "::Project_1::SphereColoringModule1::outData")
mmCreateCall("CallSpheres", "::Project_1::SphereColoringModule1::inData", "::Project_1::ASCIISphereLoader1::getdata")
mmCreateCall("CallRenderView", "::Project_1::GUIView1::renderview", "::Project_1::View3D_21::render")
mmCreateCall("CallRender3D_2", "::Project_1::View3D_21::rendering", "::Project_1::BoundingBoxRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::Project_1::BoundingBoxRenderer1::chainRendering", "::Project_1::SimplestSphereRenderer1::rendering")
