mmCreateView("mm101", "GUIView", "gui")
mmCreateModule("SimplestSphereRenderer", "::mm101::renderer")
mmCreateModule("ASCIISphereLoader", "::mm101::dataloader")
mmCreateModule("View3D", "::mm101::view")
mmSetParamValue("::mm101::view::backCol", "white")
mmSetParamValue("::mm101::view::bboxCol", "#eeeeee")
mmCreateModule("SphereColoringModule", "::mm101::coloring")
mmSetParamValue("::mm101::coloring::minColor", "white")
mmSetParamValue("::mm101::coloring::maxColor", "red")
mmCreateCall("CallRender3D", "::mm101::view::rendering", "::mm101::renderer::rendering")
mmCreateCall("CallSpheres", "::mm101::coloring::inData", "::mm101::dataloader::getdata")
mmCreateCall("CallSpheres", "::mm101::renderer::inData", "::mm101::coloring::outData")
mmCreateCall("CallRenderView", "::mm101::gui::renderview", "::mm101::view::render")
mmSetParamValue("::mm101::dataloader::filename", "megamol101/1m40.csv")