--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "D:\sellendk\Examples\QuartzRendererExamples\QuartzTexRenderer.lua" -i Project_1 inst
in PowerShell:
  -p "D:\sellendk\Examples\QuartzRendererExamples\QuartzTexRenderer.lua" -i Project_1 inst

 --]]

mmCreateView("Project_1", "GUIView", "GUIView1") --confPos={X=22,Y=18}
mmCreateModule("View3D_2", "::Project_1::View3D_21") --confPos={X=24,Y=138}
mmCreateModule("BoundingBoxRenderer", "::Project_1::BoundingBoxRenderer1") --confPos={X=20,Y=262}
mmCreateModule("QuartzTexRenderer", "::Project_1::QuartzTexRenderer1") --confPos={X=257,Y=401}
mmSetParamValue("::Project_1::QuartzTexRenderer1::correctPBC", [=[False]=])
mmCreateModule("PointLight", "::Project_1::PointLight1") --confPos={X=520,Y=123}
mmSetParamValue("::Project_1::PointLight1::Position", [=[10.000000;10.000000;10.000000]=])
mmCreateModule("QuartzDataGridder", "::Project_1::QuartzDataGridder1") --confPos={X=641,Y=404}
mmSetParamValue("::Project_1::QuartzDataGridder1::gridsizex", [=[1]=])
mmSetParamValue("::Project_1::QuartzDataGridder1::gridsizey", [=[1]=])
mmSetParamValue("::Project_1::QuartzDataGridder1::gridsizez", [=[1]=])
mmCreateModule("QuartzCrystalDataSource", "::Project_1::QuartzCrystalDataSource1") --confPos={X=775,Y=577}
mmSetParamValue("::Project_1::QuartzCrystalDataSource1::filename", [=[../examples/pwdemos/Q_param.txt]=])
mmCreateModule("QuartzParticleFortLoader", "::Project_1::QuartzParticleFortLoader1") --confPos={X=830,Y=291}
mmSetParamValue("::Project_1::QuartzParticleFortLoader1::positionFile", [=[../examples/pwdemos/objects.dat]=])
mmSetParamValue("::Project_1::QuartzParticleFortLoader1::attributeFile", [=[../examples/pwdemos/objdfns.dat]=])
mmCreateModule("PointLight", "::Project_1::PointLight2") --confPos={X=786,Y=121}
mmSetParamValue("::Project_1::PointLight2::Position", [=[10.000000;10.000000;10.000000]=])
mmCreateCall("CallRenderView", "::Project_1::GUIView1::renderview", "::Project_1::View3D_21::render")
mmCreateCall("CallRender3D_2", "::Project_1::View3D_21::rendering", "::Project_1::BoundingBoxRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::Project_1::BoundingBoxRenderer1::chainRendering", "::Project_1::QuartzTexRenderer1::rendering")
mmCreateCall("CallLight", "::Project_1::QuartzTexRenderer1::lights", "::Project_1::PointLight1::deployLightSlot")
mmCreateCall("QuartzParticleGridDataCall", "::Project_1::QuartzTexRenderer1::datain", "::Project_1::QuartzDataGridder1::dataout")
mmCreateCall("QuartzCrystalDataCall", "::Project_1::QuartzTexRenderer1::typesin", "::Project_1::QuartzCrystalDataSource1::dataout")
mmCreateCall("QuartzCrystalDataCall", "::Project_1::QuartzDataGridder1::crysin", "::Project_1::QuartzCrystalDataSource1::dataout")
mmCreateCall("QuartzParticleDataCall", "::Project_1::QuartzDataGridder1::datain", "::Project_1::QuartzParticleFortLoader1::dataout")
mmCreateCall("CallLight", "::Project_1::PointLight1::getLightSlot", "::Project_1::PointLight2::deployLightSlot")
