mmCreateView("scv", "SimpleClusterView", "scview")
mmCreateModule("SimpleClusterClient", "::scc")
mmCreateModule("View3DGL", "::logo")
mmCreateCall("SimpleClusterClientViewRegistration", "::scv::scview::register", "::scc::registerView")
mmCreateCall("CallRenderViewGL", "::scv::scview::renderView", "::logo::render")