--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "D:\sellendk\megamol\bin\simpleclusterview.lua" -i Project_3 inst
in PowerShell:
  -p "D:\sellendk\megamol\bin\simpleclusterview.lua" -i Project_3 inst

 --]]

mmCreateView("Project_3", "SimpleClusterView", "SimpleClusterView1") --confPos={X=34,Y=105}
mmCreateModule("SimpleClusterClient", "::Project_3::SimpleClusterClient1") --confPos={X=303,Y=209}
mmCreateModule("View3D_2", "::Project_3::View3D_21") --confPos={X=293,Y=28}
mmCreateCall("SimpleClusterClientViewRegistration", "::Project_3::SimpleClusterView1::register", "::Project_3::SimpleClusterClient1::registerView")
mmCreateCall("CallRenderView", "::Project_3::SimpleClusterView1::renderView", "::Project_3::View3D_21::render")
