--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "D:\sellendk\megamol\bin\testspheres.lua" -i Project_1 inst
in PowerShell:
  -p "D:\sellendk\megamol\bin\testspheres.lua" -i Project_1 inst

 --]]

mmCreateView("Project_1", "GUIView", "GUIView1") --confPos={X=10,Y=10}
mmCreateModule("View3D_2", "::Project_1::View3D_21") --confPos={X=12,Y=125}
mmCreateModule("BoundingBoxRenderer", "::Project_1::BoundingBoxRenderer1") --confPos={X=12,Y=238}
mmCreateModule("DistantLight", "::Project_1::DistantLight1") --confPos={X=633,Y=91}
mmCreateModule("TestSpheresDataSource", "::Project_1::TestSpheresDataSource1") --confPos={X=625,Y=417}
mmCreateModule("SphereRenderer", "::Project_1::SphereRenderer1") --confPos={X=324,Y=238}
mmCreateCall("CallRenderView", "::Project_1::GUIView1::renderview", "::Project_1::View3D_21::render")
mmCreateCall("CallRender3D_2", "::Project_1::View3D_21::rendering", "::Project_1::BoundingBoxRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::Project_1::BoundingBoxRenderer1::chainRendering", "::Project_1::SphereRenderer1::rendering")
mmCreateCall("CallLight", "::Project_1::SphereRenderer1::lights", "::Project_1::DistantLight1::deployLightSlot")
mmCreateCall("MultiParticleDataCall", "::Project_1::SphereRenderer1::getdata", "::Project_1::TestSpheresDataSource1::getData")
