--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "D:\sellendk\Examples\TriSoupLinesRendererExamples\trisoupstl.lua" -i Project_1 inst
in PowerShell:
  -p "D:\sellendk\Examples\TriSoupLinesRendererExamples\trisoupstl.lua" -i Project_1 inst

 --]]

mmCreateView("Project_1", "GUIView", "GUIView1") --confPos={X=16,Y=19}
mmCreateModule("View3D_2", "::Project_1::View3D_21") --confPos={X=19,Y=139}
mmCreateModule("TriSoupRenderer", "::Project_1::TriSoupRenderer1") --confPos={X=28,Y=264}
mmCreateModule("STLDataSource", "::Project_1::STLDataSource1") --confPos={X=348,Y=281}
mmSetParamValue("::Project_1::STLDataSource1::STL file", [=[D:\sellendk\Examples\TriSoupLinesRendererExamples\Wolf_One_stl.stl]=])
mmCreateCall("CallRenderView", "::Project_1::GUIView1::renderview", "::Project_1::View3D_21::render")
mmCreateCall("CallRender3D_2", "::Project_1::View3D_21::rendering", "::Project_1::TriSoupRenderer1::rendering")
mmCreateCall("CallTriMeshData", "::Project_1::TriSoupRenderer1::getData", "::Project_1::STLDataSource1::mesh_data")
