--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "T:\MegaMolExamples\protein\sombrero.lua" -i test_2050 inst
in PowerShell:
  -p "T:\MegaMolExamples\protein\sombrero.lua" -i test_2050 inst

 --]]

mmCreateView("test_2050", "GUIView", "GUIView1")
mmCreateModule("MSMSMeshLoader", "::test_2050::MSMSMeshLoader1")
mmSetParamValue("::test_2050::MSMSMeshLoader1::color::colorTableFilename", "..\\sampledata\\colormap_red.txt")
mmSetParamValue("::test_2050::MSMSMeshLoader1::MSMS_probeRadius", "2")
mmSetParamValue("::test_2050::MSMSMeshLoader1::color::coloringMode0", "17")
mmSetParamValue("::test_2050::MSMSMeshLoader1::color::coloringMode1", "17")
mmSetParamValue("::test_2050::MSMSMeshLoader1::color::colorWeighting", "1")
mmSetParamValue("::test_2050::MSMSMeshLoader1::color::midGradColor", "lightgrey")
mmCreateModule("PDBLoader", "::test_2050::PDBLoader1")
mmSetParamValue("::test_2050::PDBLoader1::pdbFilename", "..\\sampledata\\1tca_2050.pdb")
mmSetParamValue("::test_2050::PDBLoader1::strideFlag", "False")
mmCreateModule("CaverTunnelResidueLoader", "::test_2050::CaverTunnelResidueLoader1")
mmSetParamValue("::test_2050::CaverTunnelResidueLoader1::filename", "..\\sampledata\\1tca_residues.txt")
mmSetParamValue("::test_2050::CaverTunnelResidueLoader1::tunnelFilename", "..\\sampledata\\1tca_tunnel_profiles.csv")
mmCreateModule("View3D", "::test_2050::View3D1")
mmSetParamValue("::test_2050::View3D1::backCol", "white")
mmSetParamValue("::test_2050::View3D1::showBBox", "False")
mmCreateModule("TunnelCutter", "::test_2050::TunnelCutter1")
mmSetParamValue("::test_2050::TunnelCutter1::growSize", "10")
mmCreateModule("SombreroWarper", "::test_2050::ASombreroWarper1")
mmSetParamValue("::test_2050::ASombreroWarper1::invertNormals", "True")
mmCreateModule("BindingSiteDataSource", "::test_2050::BindingSiteDataSource1")
mmSetParamValue("::test_2050::BindingSiteDataSource1::pdbFilename", "..\\sampledata\\1tca_bindingsiteX.pdb")
mmSetParamValue("::test_2050::BindingSiteDataSource1::ColorTableFilename", "..\\sampledata\\colormap_red.txt")
mmSetParamValue("::test_2050::BindingSiteDataSource1::enzymeMode", "True")
mmCreateModule("SombreroMeshRenderer", "::test_2050::SombreroMeshRenderer1")
mmSetParamValue("::test_2050::SombreroMeshRenderer1::backstyle", "0")
mmCreateModule("MSMSMeshLoader", "::test_2050::MSMSMeshLoader2")
mmSetParamValue("::test_2050::MSMSMeshLoader2::color::colorTableFilename", "..\\sampledata\\colormap_red.txt")
mmSetParamValue("::test_2050::MSMSMeshLoader2::MSMS_probeRadius", "10")
mmSetParamValue("::test_2050::MSMSMeshLoader2::color::colorWeighting", "0.2")
mmCreateModule("MSMSCavityFinder", "::test_2050::MSMSCavityFinder1")
mmCreateCall("CallTriMeshData", "::test_2050::TunnelCutter1::dataIn", "::test_2050::MSMSMeshLoader1::getdata")
mmCreateCall("TunnelResidueDataCall", "::test_2050::TunnelCutter1::tunnelIn", "::test_2050::CaverTunnelResidueLoader1::getData")
mmCreateCall("MolecularDataCall", "::test_2050::MSMSMeshLoader1::moldata", "::test_2050::PDBLoader1::dataout")
mmCreateCall("MolecularDataCall", "::test_2050::TunnelCutter1::molIn", "::test_2050::PDBLoader1::dataout")
mmCreateCall("BindingSiteCall", "::test_2050::TunnelCutter1::bsIn", "::test_2050::BindingSiteDataSource1::dataout")
mmCreateCall("BindingSiteCall", "::test_2050::MSMSMeshLoader1::getBindingSites", "::test_2050::BindingSiteDataSource1::dataout")
mmCreateCall("TunnelResidueDataCall", "::test_2050::ASombreroWarper1::tunnelIn", "::test_2050::CaverTunnelResidueLoader1::getData")
mmCreateCall("CallRender3D", "::test_2050::View3D1::rendering", "::test_2050::SombreroMeshRenderer1::rendering")
mmCreateCall("MolecularDataCall", "::test_2050::MSMSMeshLoader2::moldata", "::test_2050::PDBLoader1::dataout")
mmCreateCall("BindingSiteCall", "::test_2050::MSMSMeshLoader2::getBindingSites", "::test_2050::BindingSiteDataSource1::dataout")
mmCreateCall("CallTriMeshData", "::test_2050::MSMSCavityFinder1::innerDataIn", "::test_2050::MSMSMeshLoader1::getdata")
mmCreateCall("CallTriMeshData", "::test_2050::MSMSCavityFinder1::outerDataIn", "::test_2050::MSMSMeshLoader2::getdata")
mmCreateCall("CallTriMeshData", "::test_2050::TunnelCutter1::cavityMeshIn", "::test_2050::MSMSCavityFinder1::getData")
mmCreateCall("CallTriMeshData", "::test_2050::ASombreroWarper1::dataIn", "::test_2050::TunnelCutter1::getData")
mmCreateCall("CallTriMeshData", "::test_2050::SombreroMeshRenderer1::getData", "::test_2050::ASombreroWarper1::getData")
mmCreateCall("CallRenderView", "::test_2050::GUIView1::renderview", "::test_2050::View3D1::render")
