mmCreateView("GraphEntry_1","View3DGL","::View3DGL_1")

mmCreateModule("SphereRenderer","::SphereRenderer_1")
mmCreateModule("TableToParticles","::TableToParticles_1")
mmCreateModule("DistantLight","::DistantLight_1")
mmCreateModule("CSVFileSequence","::CSVFileSequence_1")
mmCreateModule("CSVDataSource","::CSVDataSource_1")
mmCreateModule("CSVWriter","::CSVWriter_1")
mmCreateModule("ParticlesToTable","::ParticlesToTable_1")
mmCreateModule("TestSpheresDataSource","::TestSpheresDataSource_1")

mmCreateCall("CallRender3DGL","::View3DGL_1::rendering","::SphereRenderer_1::rendering")
mmCreateCall("MultiParticleDataCall","::SphereRenderer_1::getdata","::TableToParticles_1::multidata")
mmCreateCall("CallLight","::SphereRenderer_1::lights","::DistantLight_1::deployLightSlot")
mmCreateCall("TableDataCall","::TableToParticles_1::floattable","::CSVFileSequence_1::outData")
mmCreateCall("TableDataCall","::CSVFileSequence_1::inData","::CSVDataSource_1::getData")
mmCreateCall("TableDataCall","::CSVWriter_1::inData","::ParticlesToTable_1::floattable")
mmCreateCall("MultiParticleDataCall","::ParticlesToTable_1::particles","::TestSpheresDataSource_1::getData")

mmSetParamValue("::View3DGL_1::anim::speed",[=[1.000000]=])
mmSetParamValue("::View3DGL_1::anim::time",[=[3]=])
mmSetParamValue("::TableToParticles_1::redcolumnname",[=[r]=])
mmSetParamValue("::TableToParticles_1::greencolumnname",[=[g]=])
mmSetParamValue("::TableToParticles_1::bluecolumnname",[=[b]=])
mmSetParamValue("::TableToParticles_1::intensitycolumnname",[=[i]=])
mmSetParamValue("::TableToParticles_1::colormode",[=[RGB]=])
mmSetParamValue("::TableToParticles_1::radiuscolumnname",[=[rad]=])
mmSetParamValue("::TableToParticles_1::xcolumnname",[=[x]=])
mmSetParamValue("::TableToParticles_1::ycolumnname",[=[y]=])
mmSetParamValue("::TableToParticles_1::zcolumnname",[=[z]=])
mmSetParamValue("::CSVFileSequence_1::fileNameTemplate",[=[../examples/sampledata/csv_sequence/testspheres.*{0..5+1}*.csv]=])
mmSetParamValue("::CSVFileSequence_1::fileNumberMax",[=[5]=])
mmSetParamValue("::CSVFileSequence_1::fileNameSlotName",[=[::CSVDataSource_1::filename]=])
mmSetParamValue("::CSVWriter_1::filename",[=[testspheres.5.csv]=])
mmSetParamValue("::TestSpheresDataSource_1::numSpheres",[=[30]=])
