
mmCreateView("GraphEntry_1","View3DGL","::view")

mmCreateModule("BoundingBoxRenderer","::bbox")
mmCreateModule("TestSpheresDataSource","::data")
mmCreateModule("OptixRenderer","::renderer")
mmCreateModule("CUDAToGL","::cu2gl")
mmCreateModule("SphereGeometry","::sphere_geo")

mmCreateCall("CallRender3DGL","::view::rendering","::bbox::rendering")
mmCreateCall("CallRender3DGL","::bbox::chainRendering","::cu2gl::rendering")
mmCreateCall("CallGeometry","::renderer::inGeo","::sphere_geo::outGeo")
mmCreateCall("CallRender3DCUDA","::cu2gl::getContext","::renderer::rendering")
mmCreateCall("MultiParticleDataCall","::sphere_geo::inData","::data::getData")

mmSetParamValue("::view::camstore::settings",[=[]=])
mmSetParamValue("::view::camstore::overrideSettings",[=[false]=])
mmSetParamValue("::view::camstore::autoSaveSettings",[=[false]=])
mmSetParamValue("::view::camstore::autoLoadSettings",[=[true]=])
mmSetParamValue("::view::resetViewOnBBoxChange",[=[false]=])
mmSetParamValue("::view::showLookAt",[=[false]=])
mmSetParamValue("::view::view::showViewCube",[=[false]=])
mmSetParamValue("::view::anim::play",[=[false]=])
mmSetParamValue("::view::anim::speed",[=[4.000000]=])
mmSetParamValue("::view::anim::time",[=[0.000000]=])
mmSetParamValue("::view::backCol",[=[#000020]=])
mmSetParamValue("::view::viewKey::MoveStep",[=[0.500000]=])
mmSetParamValue("::view::viewKey::RunFactor",[=[2.000000]=])
mmSetParamValue("::view::viewKey::AngleStep",[=[90.000000]=])
mmSetParamValue("::view::viewKey::FixToWorldUp",[=[true]=])
mmSetParamValue("::view::viewKey::MouseSensitivity",[=[3.000000]=])
mmSetParamValue("::view::viewKey::RotPoint",[=[Look-At]=])
mmSetParamValue("::view::view::cubeOrientation",[=[0;0;0;1]=])
mmSetParamValue("::view::view::defaultView",[=[FACE - Front]=])
mmSetParamValue("::view::view::defaultOrientation",[=[Top]=])
mmSetParamValue("::view::cam::position",[=[0;0;4.91631746]=])
mmSetParamValue("::view::cam::orientation",[=[0;-0;-0;1]=])
mmSetParamValue("::view::cam::projectiontype",[=[Perspective]=])
mmSetParamValue("::view::cam::nearplane",[=[3.916317]=])
mmSetParamValue("::view::cam::farplane",[=[5.916317]=])
mmSetParamValue("::view::cam::halfaperturedegrees",[=[28.647890]=])
mmSetParamValue("::bbox::enableBoundingBox",[=[true]=])
mmSetParamValue("::bbox::boundingBoxColor",[=[#ffffff]=])
mmSetParamValue("::bbox::smoothLines",[=[true]=])
mmSetParamValue("::bbox::enableViewCube",[=[false]=])
mmSetParamValue("::bbox::viewCubePosition",[=[top right]=])
mmSetParamValue("::bbox::viewCubeSize",[=[100]=])
mmSetParamValue("::data::numSpheres",[=[15]=])
mmSetParamValue("::data::numFrames",[=[100]=])
mmSetParamValue("::renderer::spp",[=[1]=])
mmSetParamValue("::renderer::max bounces",[=[0]=])
mmSetParamValue("::renderer::accumulate",[=[true]=])
mmSetParamValue("::renderer::intensity",[=[40.000000]=])

