--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "F:\Uni\HiWi\Testing\bin\raycast_volume_renderer.lua" -i RaycastVolumeExample inst
in PowerShell:
  -p "F:\Uni\HiWi\Testing\bin\raycast_volume_renderer.lua" -i RaycastVolumeExample inst

 --]]

mmCreateView("RaycastVolumeExample", "GUIView", "GUIView1") --confPos={X=21,Y=19}
mmCreateModule("View3D_2", "::RaycastVolumeExample::View3D_21") --confPos={X=26,Y=152}
mmCreateModule("BoundingBoxRenderer", "::RaycastVolumeExample::BoundingBoxRenderer1") --confPos={X=23,Y=288}
mmCreateModule("RaycastVolumeRenderer", "::RaycastVolumeExample::RaycastVolumeRenderer1") --confPos={X=352,Y=267}
mmSetParamValue("::RaycastVolumeExample::RaycastVolumeRenderer1::ray step ratio", [=[0.1]=])
mmCreateModule("TransferFunction", "::RaycastVolumeExample::TransferFunction1") --confPos={X=702,Y=404}
mmSetParamValue("::RaycastVolumeExample::TransferFunction1::TransferFunction", [=[{"Interpolation":"LINEAR","Nodes":[[0.0,0.0,0.0,0.0,0.0,0.05000000074505806],[0.14127187430858612,0.5980616211891174,0.1649588644504547,0.07333332300186157,0.18036529421806335,0.05000000074505806],[0.45831984281539917,0.21742291748523712,0.1543489694595337,0.3399999737739563,0.3076712191104889,0.05000000074505806],[0.6666666269302368,0.6666666269302368,0.6666666269302368,0.40666669607162476,0.5452054738998413,0.05000000074505806],[1.0,1.0,1.0,1.0,1.0,0.05000000074505806]],"TextureSize":256,"ValueRange":[0.0,0.004999999888241291]}]=])
mmCreateModule("VolumetricDataSource", "::RaycastVolumeExample::VolumetricDataSource1") --confPos={X=676,Y=176}
mmSetParamValue("::RaycastVolumeExample::VolumetricDataSource1::FileName", [=[../examples/sampledata/bonsai.dat]=])
mmCreateModule("ScreenShooter", "::RaycastVolumeExample::ScreenShooter1") --confPos={X=3699,Y=0}
mmSetParamValue("::RaycastVolumeExample::ScreenShooter1::view", [=[::RaycastVolumeExample::View3D_21]=])
mmSetParamValue("::RaycastVolumeExample::ScreenShooter1::imgWidth", [=[1920]=])
mmSetParamValue("::RaycastVolumeExample::ScreenShooter1::imgHeight", [=[1080]=])
mmSetParamValue("::RaycastVolumeExample::ScreenShooter1::tileWidth", [=[1920]=])
mmSetParamValue("::RaycastVolumeExample::ScreenShooter1::tileHeight", [=[1080]=])
mmSetParamValue("::RaycastVolumeExample::ScreenShooter1::filename", [=[RaycastVolumeRenderer.png]=])
mmCreateCall("CallGetTransferFunction", "::RaycastVolumeExample::RaycastVolumeRenderer1::getTranfserFunction", "::RaycastVolumeExample::TransferFunction1::gettransferfunction")
mmCreateCall("VolumetricDataCall", "::RaycastVolumeExample::RaycastVolumeRenderer1::getData", "::RaycastVolumeExample::VolumetricDataSource1::GetData")
mmCreateCall("CallRenderView", "::RaycastVolumeExample::GUIView1::renderview", "::RaycastVolumeExample::View3D_21::render")
mmCreateCall("CallRender3D_2", "::RaycastVolumeExample::View3D_21::rendering", "::RaycastVolumeExample::BoundingBoxRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::RaycastVolumeExample::BoundingBoxRenderer1::chainRendering", "::RaycastVolumeExample::RaycastVolumeRenderer1::rendering")
