--[[ generated by MegaMol Configurator 1.3.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "F:\Uni\HiWi\vtkm\build\examples\mmvtkm\vtkm_file_renderer.lua" -i Project_1 inst
in PowerShell:
  -p "F:\Uni\HiWi\vtkm\build\examples\mmvtkm\vtkm_file_renderer.lua" -i Project_1 inst

 --]]

mmCreateView("Project_1", "GUIView", "GUIView1") --confPos={X=10,Y=10}
mmCreateModule("View3D_2", "::Project_1::View3D_21") --confPos={X=28,Y=141}
mmCreateModule("vtkmDataRenderer", "::Project_1::vtkmDataRenderer1") --confPos={X=363,Y=280}
mmCreateModule("vtkmFileLoader", "::Project_1::vtkmFileLoader1") --confPos={X=664,Y=300}
mmSetParamValue("::Project_1::vtkmFileLoader1::filename", [=[..\examples\mmvtkm\vtkm_grid.vtk]=])
mmCreateModule("BoundingBoxRenderer", "::Project_1::BoundingBoxRenderer1") --confPos={X=37,Y=282}
mmCreateCall("CallRenderView", "::Project_1::GUIView1::renderview", "::Project_1::View3D_21::render")
mmCreateCall("vtkmDataCall", "::Project_1::vtkmDataRenderer1::getData", "::Project_1::vtkmFileLoader1::getdata")
mmCreateCall("CallRender3D_2", "::Project_1::View3D_21::rendering", "::Project_1::BoundingBoxRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::Project_1::BoundingBoxRenderer1::chainRendering", "::Project_1::vtkmDataRenderer1::rendering")
