mmCreateView("Project_1", "GUIView", "GUIView1")
mmCreateModule("CSVDataSource", "::Project_1::CSVDataSource1")
mmSetParamValue("::Project_1::CSVDataSource1::filename", "..\\examples\\sampledata\\ellipsoids.txt")
mmCreateModule("TableToParticles", "::Project_1::TableToParticles1")
mmSetParamValue("::Project_1::TableToParticles1::radius", "1")
mmSetParamValue("::Project_1::TableToParticles1::radiusmode", "1")
mmSetParamValue("::Project_1::TableToParticles1::xcolumnname", "x")
mmSetParamValue("::Project_1::TableToParticles1::ycolumnname", "y")
mmSetParamValue("::Project_1::TableToParticles1::zcolumnname", "z")
mmSetParamValue("::Project_1::TableToParticles1::tensor::x1columnname", "x1")
mmSetParamValue("::Project_1::TableToParticles1::tensor::y1columnname", "y1")
mmSetParamValue("::Project_1::TableToParticles1::tensor::z1columnname", "z1")
mmSetParamValue("::Project_1::TableToParticles1::tensor::x2columnname", "x2")
mmSetParamValue("::Project_1::TableToParticles1::tensor::y2columnname", "y2")
mmSetParamValue("::Project_1::TableToParticles1::tensor::z2columnname", "z2")
mmSetParamValue("::Project_1::TableToParticles1::tensor::x3columnname", "x3")
mmSetParamValue("::Project_1::TableToParticles1::tensor::y3columnname", "y3")
mmSetParamValue("::Project_1::TableToParticles1::tensor::z3columnname", "z3")
mmSetParamValue("::Project_1::TableToParticles1::tensor::magnitude1", "rx")
mmSetParamValue("::Project_1::TableToParticles1::tensor::magnitude2", "ry")
mmSetParamValue("::Project_1::TableToParticles1::tensor::magnitude3", "rz")
mmCreateModule("EllipsoidRenderer", "::Project_1::EllipsoidRenderer1")
mmCreateModule("View3DGL", "::Project_1::View3DGL1")
mmCreateCall("TableDataCall", "::Project_1::TableToParticles1::floattable", "::Project_1::CSVDataSource1::getData")
mmCreateCall("EllipsoidalParticleDataCall", "::Project_1::EllipsoidRenderer1::getData", "::Project_1::TableToParticles1::multidata")
mmCreateCall("CallRender3DGL", "::Project_1::View3DGL1::rendering", "::Project_1::EllipsoidRenderer1::rendering")
mmCreateCall("CallRenderViewGL", "::Project_1::GUIView1::renderview", "::Project_1::View3DGL1::render")
